MiSTer-devel/ao486_MiSTer

rtl/ao486/pipeline/execute_shift.v

The original shifter code selects shifter results using nested ternary statements. This leads to a long chain of conditionals. This is now restructured to using case statements, which are "wider", but less "deep". Apart from case-statements perhaps being the natural choice, the less "deep" chain of logic might relax timing.
For now, both the original code and the restructured code are included and can be selected via defines. **In the future, the unused code path can be removed.**
Overview of the original "ternary" shifter:
Overview of the "case" shifter
There's still quite some "stringiness" remaining (the logic selecting the shifter inputs), so there might still be room for further changes.

 execute_shift.v: restructure shifter

---

rtl/soc/joystick.v

This should improve non-Gravis pro joysticks accuracy on all core frequencies. This may fix #30 . I have not been able to fully compile the core (synthesis passes, fitting fails) so I was not able to fully confirm the fix.

soc/joystick: Only report axes for joysticks which are actually plugged

---

ao486.qsf
rtl/soc/sound/sound_dsp.v

This change addresses some games that freeze because the DSP and game are deadlocked waiting on each other. The focus was to fix the freezing seen in The Secret of Monkey Island, but the change is not specific to it. It will probably improve other games as well.

sound: Add busy wait to write port status on DSP

---

ao486.qsf

Current fitter settings were not putting enough effort by Quartus into timing performance or the fit. 8.0x effort multiplier and physical synthesis effort settings increase the effort to fit, initial default seed "1" yielded a successful compile for the first time I've ever seen. QII_AUTO_PACKED_REGISTERS, according to the tooltip says "SPARSE AUTO" to be the best effort at timing performance, and this core needs every bit of timing performance.
I am currently running a 100 seed run in DSE to find out what the best seed is for this build in terms of timing and fmax. When that is completed in a few days I will update this PR with that seed so it can be compiled, along with the test results as documentation in a reply.
I have been testing these improved fitter settings for a few weeks with …

exploration: potential improvement to fitter settings

---

rtl/soc/ps2.v
sw/sysbios/rombios.c

With the framework duly updated, an actual change to scancode set 1 is now made instead of a scancode translation. Thank you @naeloob for your cooperation and support in developing this feature.

Scancode set 1 switching

---

rtl/system.v

This is a partial fix for #103 and allows reading of floppy disks under Windows NT.
I have found that the CS signals for ide0 and floppy0 were overlapping, and this was blocking the system from properly accessing the floppy controller's "Digital Input Register" (at 0x3F7) where the "disk changed" flag is read from. This flag is not used by DOS or Windows 95, but is used by NT and Linux. I have updated the mappings of the CS signals to match that expected by the  original hardware.
**Old I/O mappings:** 
IDE0: 0x1F0-0x1F7 and 0x3F6-0x3F**7**
IDE1: 0x170-0x177 and 0x376-0x377
Floppy: 0x3F0-0x3F**7**
**New I/O mappings:**
IDE0: 0x1F0-0x1F7 and 0x3F6
IDE1: 0x170-0x177 and 0x376
Floppy: 0x3F0-0x3F5 and 0x3F7
Note that further work is needed around reset_changeline in floppy.v, as the flag is …

Fix overlapping CS for IDE and Floppy

---

ao486.sv

They have the same file structure as IMG images. I tested with images created with WinImage to be sure this worked. It also works to just rename the images, but might as well support more image types.

Add support for mounting IMA and VFD floppy image files

---

sw/MiSTerFS/MiSTerFS.C

Removed the packet driver logic from the unload option (misterfs.exe /u). The packet driver routine doesn't exist in MiSTerFS and it was causing a crash when trying to unload it.
The unload code was also updated to not use a hard coded offset of 24. This offset was correct, but it was updated to be more consistent with how the initialization code searched for the correct offset.
Comments and formatting were updated.

MiSTerFS: Fix for divide by zero crash when trying to unload the filesystem.

---

rtl/soc/sound/sound.v
rtl/soc/sound/sound_dsp.v

Previously the write port status busy flag was set on any DMA
request, and then cleared when the software polled for the
status. This caused problems with software using auto-init DMA
because the busy flag may be reset by the new transfer before
it polled a second time resulting in the DSP always returning
busy.
The logic was updated to instead use a fixed busy timer that
clears independently from the software polling for status.
Fixes MiSTer-devel/ao486_MiSTer#117

sound: Updated the DSP write port status busy flag

---

rtl/soc/joystick.v

This allows joysticks to report immediately rather than waiting for button press. This fixes a lot of user confusion and missed joystick detection/calibration for games and for boot menus.
If it turns out joysticks NEED to be disabled for some game, an option can be added to disable them.

allow joystick to report immediately

---

rtl/soc/sound/opl3/host_if.sv
rtl/soc/sound/opl3/trick_sw_detection.sv
rtl/soc/sound/sound.v

Decompiled Doom OPL3 detection routine for `DMXOPTION=-opl3-phase` provided by Never_Again at https://www.vogons.org/viewtopic.php?f=7&t=100285. This env var now gets picked up by Doom and we finally have stereo!
The timing improvements came with some nice area reductions.
Made normal adlib detection routine slightly more robust as well.

Fix Doom OPL3 detection, timing improvements

---

rtl/soc/sound/opl3/channels.sv
rtl/soc/sound/opl3/control_operators.sv
rtl/soc/sound/opl3/envelope_generator.sv
rtl/soc/sound/opl3/host_if.sv
rtl/soc/sound/opl3/mem_multi_bank_reset.sv
rtl/soc/sound/opl3/operator.sv
rtl/soc/sound/opl3/opl3.qip
rtl/soc/sound/opl3/phase_generator.sv

Waveform 6 (square wave) had no envelope applied to it so was full blast. Test case was Cybersphere, go to options menu and let it play.
Reset now brings all operator envelopes into the RELEASE state, stopping music on reset.

Fix waveform #6, reset envelope on all operators

---

rtl/soc/sound/opl3/host_if.sv
rtl/soc/sound/opl3/trick_sw_detection.sv

Adlib detection broke in oplclone and Day of the Tentacle after recent timing improvements. Needed to return read value 1 cycle sooner. Additional register on host_status seemed to help timing, so this doesn't look to be degraded timing-wise.

Fix trick sw detection

---

rtl/soc/sound/opl3/mem_multi_bank.sv
rtl/soc/sound/opl3/mem_multi_bank_reset.sv
rtl/soc/sound/opl3/mem_simple_dual_port_async_read.sv
rtl/soc/sound/opl3/opl3.qip

Savings of ~1000 ALMs give or take depending on the run. Substantial.

Infer async 0-cycle read mems in MLAB LUT RAM

---

rtl/soc/sound/opl3/channels.sv

4-operator channels were bleeding into some of the 2-operator channels, causing a slightly over-modulated sound.

Fix 4-operator mode

---

rtl/soc/sound/opl3/calc_rhythm_phase.sv
rtl/soc/sound/opl3/channels.sv
rtl/soc/sound/opl3/control_operators.sv
rtl/soc/sound/opl3/edge_detector.sv
rtl/soc/sound/opl3/env_rate_counter.sv
rtl/soc/sound/opl3/operator.sv
rtl/soc/sound/opl3/opl3_pkg.sv
rtl/soc/sound/opl3/phase_generator.sv

Rhythm operators were broken. Testcase was Adlib Jukebox, Highways.
Refactored calc_rhythm_phase and phase_generator to match implementation in https://github.com/nukeykt/Nuked-OPL3

Fix rhythm operators

---

ao486.sdc
ao486.sv
rtl/soc/sound/opl3/env_rate_counter.sv
rtl/soc/sound/opl3/opl3_pkg.sv
rtl/soc/sound/sound.v
rtl/system.v

Use clk_audio to drive OPL3 as this is what the final clock domain is anyway (removes clk_opl entirely for better overall stability as discussed with @sorgelig here https://github.com/MiSTer-devel/ao486_MiSTer/pull/157), and we already have an existing sample clock enable implemented. Using divider of 494 gets us to 49.74899KHz sample freq, +0.07% away from perfect, closer than we were after removal of OPL3 PLL.
Also fixed the SB DSP & CMS clock domain crossing from clk_sys->clk_audio. Possible reduction in noise.

Drive OPL3 off audio clock, fix SB DSP clock domain crossing

---

rtl/soc/sound/opl3/channels.sv

Games will typically clear both banks on start and exit. However, if a reset occurs during a game that is using OPL3 features and sets `new` and `connection_sel` regs in the second bank, the next game may be OPL2-only and not clear the second bank as it didn't exist on the OPL2.
Not resetting the other regs in the second bank is fine as the envelope for all operators gets reset to the RELEASE state.
I found this bug today showing someone the ao486, resetting in the middle of Doom (with DMXOPTION=-opl3-phase) and launching Indiana Jones and the Fate of Atlantis. There was no music in Indiana Jones as the `new` bit was still set and if it is at least one `cha`, `chb`, `chc`, or `chd` reg must be set for the channels to get added to the accumulator, and these regs would have gotten cleared …

Reset new and connection_sel regs specific to OPL3

---

ao486.sv
rtl/soc/vga.v
rtl/system.v

Biggest changes:
- Add border support (overscan).
- Graceful handling of odd number of overscan lines for Native mode.
- More accurate VGA timing signals.
- Added `attrib_mono_emulation` handling (MDA/Hercules emulation in mode 7).
- Reduce timing violations.
- Refactoring.
Fixes:
- Pinball Fantasies (startup delay)
- Pinball Dreams (black screen)
- #119
- #126
- Prehistorik 2 (scrolling)
- The Incredible Machine (black screen)
- Alien Carnage (flashing screen)
- others...

VGA: Add border support and various fixes

---

rtl/ao486/memory/prefetch.v

When a prefetch reset is triggered under certain conditions (in the middle of `prefetchfifo_accept_do`), the decoder can still fetch instruction bytes and will load the same bytes twice.
The bug can be replicated using the following code (compile a .COM file using e.g. NASM):
(the `C7` `MOV` instruction is where things go wrong)
`MOV_BAD.ASM`
```
org     100h
use16
nop
nop
nop
nop
nop
nop
mov     byte [cs:var_b1], 0x8
nop
inc     si
mov     word [cs:var_w1], 0xa8      ; reset_prefetch triggered here by icache
mov     word [cs:var_w2], 0xa8      ; but linear not updated correctly by prefetch
nop
nop
nop
nop
nop
jmp exit
var_b1: db 0bh
var_b2: db 0fh
var_w1: dw 01234h
var_w2: dw 0abcdh
exit:
mov ax,4C00h
int 21h
mov ax, [cs:var_b1]
mov bx, [cs:var_w1]
mov cx, [cs:var_w2]
jmp 100h
```
Note …

Prefetch: Fix prefetch reset

---

sw/sysbios/rombios.c

Issue: The high words of EAX, EBX and EDX are clobbered by `int13_harddisk`.
This can be checked by e.g. `TEST/DOSTEST.EXE` included with HX DOS Extender v2.21.
Affected games:
- Blackthorne (MS-DOS 6.22) shows corrupted player animations.

BIOS: Fix register clobbering by int13_harddisk

---

sw/sysbios/rombios.c

Some programs expect the int 13h handler to return with interrupts enabled (IF).
Affected games:
- Blackthorne (MS-DOS 6.22) hangs.
- others...

BIOS: Fix losing of interrupt flag (IF) after int13

---

rtl/cache/l2_cache.v

When the ROM region is directly writable it can be incorrectly detected as Option RAM (e.g. by EMM386).
Can also be verified with the MSD tool (memory overview) included with MS-DOS 6.22.

Memory: Improve free UMA detection

---

rtl/ao486/autogen/microcode_commands.v
rtl/ao486/commands/CMD_task_switch.txt

During TSS task switching, when reaching the step `CMDEX_task_switch_3_STEP_15`, it doesn't progress to `CMD_task_switch_4`, but hangs in `CMD_task_switch_3` (command `cond_204` stays active).
This has the effect of reading more memory until a page fault occurs. The task switch does not happen.
This fixes hangcrashes with e.g. DOS4GW, DJGPP, CWSDPMI, SoftICE and should at least also fix #128 and #39.
It also seems to reveal new issues with Windows 95.

Microcode: Fix TSS task switching (fixes e.g. DOS4GW, DJGPP, CWSDPMI)

---

rtl/ao486/autogen/write_commands.v
rtl/ao486/commands/CMD_CPUID.txt

Change the CPU's manufacturer ID string returned by CPUID (EAX=0) from "MiSTer AO486" to "GenuineIntel" to help improve compatibility.
Fixes:
- Memtest86+ v4.10
See also a forum discussion about this [here](https://misterfpga.org/viewtopic.php?t=6582).

CPUID: GenuineIntel

---

ao486.sv
rtl/cache/l2_cache.v
rtl/system.v

Adds a menu option to enable RAM in the upper memory region D0000h-EFFFFh.
Use this option with e.g. HiRAM.
Fixes: #177

Add D0000h-EFFFFh RAM option

---

rtl/ao486/autogen/write_commands.v
rtl/ao486/commands/CMD_CPUID.txt

According to AP-485 version 241618-004 "Intel Processor Identification With the CPUID Instruction" from December 1995 (e.g. the A80486SX2-50 was released in 1995) the `EBX` and `ECX` registers are Intel reserved for the CPUID leaf 1 and should not be used.
The CPUID leaf 1 should probably return `EBX=0` for a 486SX2-50.
Only later (introduced in the Pentium processor?) the CPUID leaf 1 returned additional information in the `EBX` register:
- `EBX[7:0]` = Brand index
- `EBX[15:8]` = CLFLUSH instruction cache line size
- `EBX[23:16]` = Logical CPU (HW threads) count
- `EBX[31:24]` = Initial local APIC physical ID

CPUID: Return EBX=0 for leaf 1

---

rtl/ao486/pipeline/write_debug.v

Resolves an issue where hardware read/write breakpoints could endlessly loop due to immediate re-triggering.
Fixes:
- Rayman

Fix hardware read/write breakpoints endless loop (fixes e.g. Rayman)

---

rtl/soc/sound/opl3/control_operators.sv
rtl/soc/sound/opl3/envelope_generator.sv

Fixes a regression in e881af1523d958e0dcda4f06f99a95deedcf717b where envelopes should go into RELEASE state instead of stay in SUSTAIN and play notes forever on reset. Key-on is no longer edge-detected so we must reset the key-on itself.
Closes https://github.com/MiSTer-devel/ao486_MiSTer/issues/174

OPL3: fix envelope RELEASE state on reset

---

rtl/soc/pit.v

The counter clock input frequency has been set to the correct value of 105/88 MHz (1193181.81818... Hz), which improves the overall accuracy of the PIT.

PIT: Set counter clock input to correct 105/88 MHz frequency

---

rtl/soc/vga.v

Fixes a bug where the VGA line compare logic failed to handle certain split screen scenarios correctly.
This change updates the line compare (split screen) logic to match the behavior of the Tseng Labs ET4000 VGA controller.
Fixes e.g. Supaplex (#196).

VGA: Fix line compare (split screen) handling

---

ao486.sv
rtl/soc/joystick.v
rtl/system.v

Fix bug in the frame identification header (5 ones after initial 0) of the Gravis Interface Protocol (GrIP) for joystick 2.
Add axes options because games often use either a timed method or count method to determine the joystick position:
- *Timed*: Simulates the time needed to charge a capacitor through the potentiometer of the joystick to determine its position, using the IBM joystick time formula for a 100 kOhm potentiometer. The timing is fixed and made independent of the CPU speed settings.
- *Count*: The joystick position is determined by the number of reads required before the signal goes low (the number of reads are counted in software and reflect the joystick position). Count 6+256 produces a base count of 6 followed by the current joystick position using a maximum resolution of …

Joystick: Fix bugs, add axes options (Timed/Count), and refactor code
